newspage_settings:
    pattern: /news/settings
    defaults: { _controller: nickvergessen.newspage.controller.settings:manage }

newspage_controller:
    pattern: /news
    defaults: { _controller: nickvergessen.newspage.controller:newspage, forum_id: 0, year: 0, month: 0, page: 1 }

newspage_page_controller:
    pattern: /news/page/{page}
    defaults: { _controller: nickvergessen.newspage.controller:newspage, forum_id: 0, year: 0, month: 0 }
    requirements:
        page:      \d+

newspage_archive_controller:
    pattern: /news/archive/{year}/{month}
    defaults: { _controller: nickvergessen.newspage.controller:newspage, forum_id: 0, page: 1 }
    requirements:
        year:      \d+
        month:     \d+

newspage_archive_page_controller:
    pattern: /news/archive/{year}/{month}/page/{page}
    defaults: { _controller: nickvergessen.newspage.controller:newspage, forum_id: 0 }
    requirements:
        year:      \d+
        month:     \d+
        page:      \d+

newspage_category_controller:
    pattern: /news/category/{forum_id}
    defaults: { _controller: nickvergessen.newspage.controller:newspage, year: 0, month: 0, page: 1 }
    requirements:
        forum_id:  \d+

newspage_category_page_controller:
    pattern: /news/category/{forum_id}/page/{page}
    defaults: { _controller: nickvergessen.newspage.controller:newspage, year: 0, month: 0 }
    requirements:
        forum_id:  \d+
        page:      \d+

newspage_category_archive_controller:
    pattern: /news/category/{forum_id}/archive/{year}/{month}
    defaults: { _controller: nickvergessen.newspage.controller:newspage, page: 1 }
    requirements:
        forum_id:  \d+
        year:      \d+
        month:     \d+

newspage_category_archive_page_controller:
    pattern: /news/category/{forum_id}/archive/{year}/{month}/page/{page}
    defaults: { _controller: nickvergessen.newspage.controller:newspage }
    requirements:
        forum_id:  \d+
        year:      \d+
        month:     \d+
        page:      \d+

newspage_singlenews_controller:
    pattern: /news/{topic_id}
    defaults: { _controller: nickvergessen.newspage.controller:single_news }
    requirements:
        topic_id:  \d+
